[metadata]
name = "github.com/northwesternmutual/kanali-plugin-apikey"

[[constraint]]
  name = "github.com/northwesternmutual/kanali"
  branch = "kanali.io/v2alpha1"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "v3.2.11"

# the following constraint must be updated
# once this PR has been merged:
# https://github.com/uber-go/zap/pull/538
[[constraint]]
  name = "go.uber.org/zap"
  branch = "grpclog-v2"
  source = "github.com/frankgreco/zap"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.1.4"
